### ISSUE TITLE
5.2.3 breaks gulp-imagemin

### ISSUE THREAD

**Issue by yadvendar** [imagemin/imagemin-svgo#30]
SVG images has broken style tags, the contents of the tag are deleted, but not the tag itself.
<defs><style/></defs>
The use of options `removeStyleElement` works correctly and either deletes the tag, or not, but the contents of the tag are cleared against the will of the development. Please refer to this [issue](https://github.com/sindresorhus/gulp-imagemin/issues/282).

gulp-imagemin relies on imagemin-svgo and it was working fine till 5.2.2 but after 5.2.3 it has started breaking off.

**Comment by andrewmee** [comment]
I've also had errors introduced by this new version with gulp-imagemin — it now removes `viewBox` by default (unless it's explicitly told not to).

This release brings in a new "major" release version of SVGO in semver (1.0 from 0.7), which represents a breaking change.  Because of that, this release should also have been marked as a major release (version 6.0.0) to correctly signal the breaking nature of this update.

I think the right thing to do in this scenario would be to either release a new version 5.2.4 which reverts these changes, or remove/unpublish this release from npm (though I believe the former method is generally advised).  Then this release can be re-released as a new major release version 6.0.0.

**Comment by kevva** [comment]
They only released a major because of the Node.js 4 requirement and the switch to a Promise based API. We already did both so I didn't see why it would need a major. I don't see any of your issues documented in their [release notes](https://github.com/svg/svgo/releases) either. Are you able to fix your issues by changing your code? I'm going to wait on reverting this one and release a major until we encounter more users with issues.

**Comment by kevva** [comment]
Never mind, I'll release a major instead. Thanks for reporting guys.

**Comment by kevva** [comment]
Fixed in https://github.com/imagemin/imagemin-svgo/commit/130da5ac38018e39a2d345b16a7907d4293ec390.

**Comment by andrewmee** [comment]
Yeah I couldn't find details in those release notes that would account for the changes we saw either - could only confirm by testing the old vs new version.

Thanks very much for your prompt rerelease! 👍
